name: 'dbt_stocks'
version: '1.0.0'
config-version: 2

profile: 'dbt_stocks'

model-paths: ["models"]

models:
  dbt_stocks:

    bronze:
      +schema: bronze
      +materialized: view

    silver:
      +schema: silver
      +materialized: table

    gold:
      +schema: gold
      +materialized: table
